### ISSUE TITLE
Nothing worked :)

### ISSUE THREAD

**Issue by vitalyster** [otalk/otalk-im-client#30]
I have prosody-0.10, all required modules, after I enter my credentials and WS Url I see "Connecting..." and then silently redirected to login page. `node server` output is empty, JS console in browser is empty, prosody log:
```
Dec 08 15:40:38 c2s85bd450      info    Client connected
Dec 08 15:40:38 mod_websocket   debug   Websocket received frame: opcode=1, 132 bytes
Dec 08 15:40:38 c2s85bd450      debug   Client sent opening <stream:stream> to xxx.yyy.zzz.aaa
Dec 08 15:40:38 c2s85bd450      debug   Sent reply <stream:stream> to client
Dec 08 15:40:38 mod_websocket   debug   Websocket received frame: opcode=1, 16 bytes
Dec 08 15:40:38 c2s85bd450      debug   Received </stream:stream>
Dec 08 15:40:38 c2s85bd450      debug   c2s stream for <xxx.yyy.zzz.aaa> closed: session closed
```
What is the problem?

**Comment by wesley-harding** [comment]
I was running into this problem and for me it looked like the authentication was failing.  Are you seeing a similar issue perhaps?

**Comment by andrey-utkin** [comment]
Same happens to me.

**Comment by vitalyster** [comment]
@andrey-utkin that error was mean otalk-client uses "old-websocket" (as specified in xmpp-websocket draft specs) transport while server want real "websocket" (RFC7395 spec). It was fixed in later versions of stanza.io library, but otalk still uses old one. Check other forks, there are updated ones.

**Comment by andrey-utkin** [comment]
@vitalyster so you don't care to update the instance on the original site?

**Comment by vitalyster** [comment]
@andrey-utkin it looks abandoned, I think original authors does not care

**Comment by andrey-utkin** [comment]
Oh sorry I thought you are maintainer )
